#!/bin/sh
cp andutils.c ../
cp compile.h ../ffmpeg/
cp cpu_id.c ../
cp dependency.c ../
cp ffplay.c ../andzop.c
cp linux_specific.c ../
cp android_specific.c ../
cp packetqueue.c ../
cp queue.c ../
cp scale.c ../
cp yuv2rgb16tab.c ../
cp utility.c ../
cp yuv420rgb8888c.c ../
cp andutils.h ../
cp cpu_id.h ../
cp dependency.h ../
cp packetqueue.h ../
cp queue.h ../
cp scale.h ../
cp yuv2rgb.h ../
cp utility.h ../
cp yuv2rgb.neon.h ../
cp libavcodec/h263.c ../ffmpeg/libavcodec/h263.c
cp libavcodec/mpeg4videodec.c ../ffmpeg/libavcodec/mpeg4videodec.c
cp libavcodec/h263dec.c ../ffmpeg/libavcodec/h263dec.c
cp libavcodec/mpegvideo.c ../ffmpeg/libavcodec/mpegvideo.c
cp libavcodec/mpeg4video.c ../ffmpeg/libavcodec/mpeg4video.c
